[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/overview.html"
  status = 200

[[redirects]]
  from = "/your-plan"
  to = "/your-plan.html"
  status = 200

[[redirects]]
  from = "/book"
  to = "/book.html"
  status = 200

[[redirects]]
  from = "/thank-you"
  to = "/thank-you.html"
  status = 200

